# Generated by Django 4.1.6 on 2023-03-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=48, unique=True)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('oxygen', models.BigIntegerField()),
                ('level', models.SmallIntegerField()),
                ('plasticSaved', models.BigIntegerField()),
                ('isAlive', models.BooleanField(default=True)),
                ('endurance', models.SmallIntegerField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
    ]
