# Generated by Django 4.1.6 on 2023-03-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_accounts_tree_delete_leaderboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='plasticSaved',
            new_name='plastic_saved',
        ),
    ]
