# Generated by Django 4.1.6 on 2023-03-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_plasticsaved_tree_plastic_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='water',
            field=models.SmallIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='tree',
            name='level',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tree',
            name='oxygen',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tree',
            name='plastic_saved',
            field=models.BigIntegerField(default=0),
        ),
    ]
