# Generated by Django 5.0.dev20230124092027 on 2023-03-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tree_water_alter_tree_level_alter_tree_oxygen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='bottle_plastic',
            field=models.IntegerField(default=500),
        ),
    ]
